name: Release
on:
  create:
    tags:
      - "dyve-[0-9]+.[0-9]+.[0-9]+"


jobs:
  release:
    runs-on: ubuntu-latest 
    steps:
      - run: |
          echo "${{github.ref}}"
      - name: Tag with only version
        id: tag
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e "s/dyve-//")
          echo "::set-output name={tag}::{${TAG}}"
          git tag "$TAG"