name: Release
on: push

jobs:
  job1: 
    runs-on: ubuntu-latest 
    steps:
      - name: Output
        id: out
        run: |
          echo "::set-output name={greet}::{hi}"
    outputs:
      greet: ${{steps.out.outputs.greet}}
  job2:
    runs-on: ubuntu-latest 
    needs:
      - job1
    steps:
      - run: |
          echo ${{needs.job1.outputs.greet}}