name: Release
on: push

jobs:
  job1: 
    runs-on: ubuntu-latest 
    outputs:
      greet: ${{steps.out.outputs.greet}}
    steps:
      - name: Output
        id: out
        run: |
          echo "::set-output name=greet::hi"
  job2:
    runs-on: ubuntu-latest 
    needs: job1
    steps:
      - run: |
          echo ${{needs.job1.outputs.greet}}